version: '3.4'

services:
  api1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  api2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"