version: '3.4'

services:
  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  api1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  api2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

