version: '3.4'

services:
  api1:
    image: ${DOCKER_REGISTRY}api1
    build:
      context: .
      dockerfile: API1/Dockerfile

  api2:
    image: ${DOCKER_REGISTRY}api2
    build:
      context: .
      dockerfile: API2/Dockerfile

  web:
    image: ${DOCKER_REGISTRY}web
    build:
      context: .
      dockerfile: Web/Dockerfile
    depends_on:
      - api1
      - api2